### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [dajare/margaret-oliphant_the-rector-and-the-doctors-family#1]
# General Issues:

- [x] There are several files where the title shows "The Rector and the Doctor’s Family" instead of "The Rector and The Doctor’s Family". You can find them by running `grep -r "The Rector and the Doctor’s Family"`.

- Make sure to also correct the alpha-sorted title.

- [x] This looks like it is part of a collection `series` rather than a `set`.

**Comment by dajare** [comment]
Thanks so much, @EmmaSweeney  - all done! (That's the first time I've twigged to the "set/series" distinction! I'll have to fix the Palliser series, from which I grabbed those lines.)

I take it you're content with the `savage` | `salvage` matter. I think I'm inclining to it reading "salvage", but I'm happy to leave that one. If Alex has a view on it, no doubt he'll act on it before release. :)

If the changes pass scrutiny, this is ready for Alex.
